---
- name: Provision EC2 instance
  hosts: localhost
  connection: local
  gather_facts: False

  vars:
    instance_type: t2.micro
    ami_id: ami-xxxxxxxx  # Replace with your desired AMI ID
    key_name: your_key_pair_name
    security_group: your_security_group_name

  tasks:
    - name: Launch EC2 instance
      ec2:
        instance_type: "{{ instance_type }}"
        image: "{{ ami_id }}"
        wait: true
        key_name: "{{ key_name }}"
        group: "{{ security_group }}"
        count: 1
        instance_tags:
          Name: web-server

    - name: Add EC2 instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groups: web_servers
      with_items: "{{ ec2.instances }}"
